lib/faraday_middleware/instrumentation.rb

After upgrading faraday to 0.9.0 and faraday_middleware to 0.9.1, I started having an issue with a gem that relies on both, [geoip2](https://github.com/YotpoLtd/geoip2), being unable to find `ActiveSupport::Notifications`:
```
NameError: uninitialized constant FaradayMiddleware::ActiveSupport::Notifications
/gems/faraday_middleware-0.9.1/lib/faraday_middleware/instrumentation.rb:25 in "call"
/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30 in "call"
/gems/faraday_middleware-0.9.1/lib/faraday_middleware/request/encode_json.rb:23 in "call"
/gems/faraday-0.9.0/lib/faraday/response.rb:8 in "call"
/gems/faraday-0.9.0/lib/faraday/request/authorization.rb:38 in "call"
/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139 in "build_response" …
```

Refer to ActiveSupport::Notifications as a top-level constant

---

lib/faraday_middleware/gzip.rb
spec/unit/gzip_spec.rb

Currently the Gzip middleware only supports the RFC compliant zlib+deflate stream format, but it should also support the raw deflate stream format adopted by some server implementations like Microsoft IIS and Rack::Deflate.
Here's some references:
- https://en.wikipedia.org/wiki/HTTP_compression#Problems_preventing_the_use_of_HTTP_compression
- https://github.com/rest-client/rest-client/issues/49
- https://github.com/lostisland/faraday_middleware/issues/119

Add support for a raw deflated stream to Gzip

---

lib/faraday_middleware/response/follow_redirects.rb
spec/unit/follow_redirects_spec.rb

We at Travis CI are great fans of Faraday. We use it all over the place, thank you so much 🎉 
We would like to respond to redirects, eg logging the event. 
This change adds an optional callback to FollowRedirects.

Add optional callback to FollowRedirects

---

lib/faraday_middleware/response/caching.rb

All checks for response properties need to be done inside on_complete
And need to actually return the response.
Related to the lack of tests for parallel mode: See #100

Fixed using Caching middleware with async adapter like Typhoeus

---

lib/faraday_middleware/response/parse_dates.rb
spec/unit/parse_dates_spec.rb

While not exhaustive, this expands support to include a larger subset ISO8601 Date formats that specify a time with zone.
In the context of Faraday, I think that this expansion is safe, but that any further assumptions about what constitutes a valid Date / Time would need to be strongly considered.

Support non-zulu times in ParseDates Middleware

---

lib/faraday_middleware/response/caching.rb

This is a slight revision to PR #121.
The change made [here](https://github.com/lostisland/faraday_middleware/pull/121/commits/9389fba5f5a15282e50f522271c7372f578b7ba1) causes issues with caches that use serialization (e.g. [redis-activesupport](https://github.com/redis-store/redis-activesupport)). Here's why:
**Original version**
Here, the response object (`Faraday::Response`) returned from `@app.call(env)` is written to cache.
```
response = @app.call(env)
response.on_complete do
cache.write(key, response)
end
```
**Current version**
Here, the env object (`Faraday::Env`) yielded from `on_complete` is written to cache.
```
@app.call(env).on_complete do |response|
cache.write(key, response)
end
```
For the purposes of saving a response, these two approaches seem interchangeable. But the …

Support response serialization in parallel caching

---

lib/faraday_middleware/response/follow_redirects.rb
spec/unit/follow_redirects_spec.rb

fixes #149, #138, #117 and #105

ignores fragments in the `Location` header on redirect responses

---

lib/faraday_middleware/response_middleware.rb
spec/unit/parse_json_spec.rb

If a `ParsingError` is raised during processing, then attach the `env.response` to the error.
Presented as an alternative to https://github.com/lostisland/faraday/pull/638.

Include env.response when rescuing ParsingErrors

---

lib/faraday_middleware/response/follow_redirects.rb
spec/unit/follow_redirects_spec.rb

This restores the behaviour we had prior to https://github.com/lostisland/faraday_middleware/commit/34c5bc1159566a5e156b75cd50f2cf4c5f00ce02.
Close #158.

Handle responses with missing Location header

---

lib/faraday_middleware/response/caching.rb
spec/unit/caching_spec.rb

`FaradayMiddleware::Caching` is configured with a cache with responds to `#read`, `#fetch` and `#write`. Usually, this will be an instance of a class which conforms to the abstract cache store class [`ActiveSupport::Cache::Store`](http://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html).
In this pattern, the third argument of `#write` is an optional hash of options - for example, you can specify an `expires_in` to set how long until the cache key expires (this is the case where we're interested for a gem I maintain, https://github.com/ejholmes/restforce). Cache stores may support a range of options.
This allows you, when configuring the middleware, to specify a set of `write_options` which will be passed in as this third argument when writing to the cache.
The alternative to …

Allow `write_options` to be specified for FaradayMiddleware::Caching

---

.travis.yml

Removes support for ruby < 1.9.3

---

lib/faraday_middleware/response/parse_json.rb
lib/faraday_middleware/response_middleware.rb
spec/unit/parse_json_spec.rb

This should fix #124 and allow all options to be passed to JSON.parse, it felt best to pass the options to the parse proc instead of overriding the parse method which was my second option and looks to be the way that the multijson middleware does it (which I am also open to doing).
Passing the options to the proc should be a non breaking change as any existing parsing middleware will continue to work as before and if required they will have access to the options argument.

Add support for passing options to JSON.parse

---

Gemfile
README.md
lib/faraday_middleware/response/rashify.rb

Since Hashie have own Rash, [rash gem](https://github.com/tcocca/rash) have problem of conflict namespace. We discussed this from long time ago.
https://github.com/tcocca/rash/issues/9
But there is not any solution, I released [rash_alt gem](https://rubygems.org/gems/rash_alt) for solving out-of-dependency.
faraday_middleware use both hashie and rash, there is problem for out-of-dependency. This pull request solve this problem.

Replace rash with rash_alt

---

Gemfile
lib/faraday_middleware/response/parse_yaml.rb

An issue from June 2014, https://github.com/lostisland/faraday_middleware/issues/92, raises the risks of the current `FaradayMiddleware::ParseYaml` middleware which uses `YAML.load`. This method is very unsafe and exposes you to remote code execution - see https://github.com/ruby/psych/issues/119 for discussion.
At the time, @mislav decided not to make this change to avoid messing with backwards compatability.
I would suggest that we should revisit this decision - the risks of this are very high, very few people are using this middleware most likely, and it doesn't seem unreasonable to break this
as long as we are clear on the change in the changelog.
This does that by using Ruby's built-in `Psych.safe_load` for Ruby 2.0.0 and onwards, or otherwise uses the `safe_yaml` gem for earlier …

Parse YAML safely

---

lib/faraday_middleware/response/parse_json.rb
lib/faraday_middleware/response_middleware.rb
spec/unit/parse_json_spec.rb

Based on the discussion in #156 I decided to take the path of least resistance and if there are no parser_options just call .parse without them, I did this instead of defaulting the options to {} to remove any other future surprises.

Handle empty parser_options more reliably

---

README.md

This PR removes a part of the README, which assisted with "ruby < 1.9", which after 0.12 release is not supported by the gem, anyway.
- [ci skip]

README: drop explanation about "ruby < 1.9"

---

README.md

This formatting and documenting PR presents the optional dependent libraries as a table.

README: Dependent library list as table

---

Gemfile
lib/faraday_middleware/gzip.rb
spec/unit/gzip_spec.rb

Brotli is a new open-source compression algorithm from Google which can
give more dense compression, while compression and decompression speeds
are roughly the same.
Brotli responses are requested by setting `Accept-Encoding: br`.
Transferring less data over the network will typically result in a
faster experience for users.
This change adds support for Brotli decompression of responses.

Add brotli support

---

.travis.yml
Gemfile
lib/faraday_middleware/gzip.rb
spec/helper.rb
spec/unit/gzip_spec.rb
spec/unit/parse_json_spec.rb

Fixes incompatibility with jruby by isolating brotli
Fixes #168

Adds support for JSON 2

---

lib/faraday_middleware/backwards_compatibility.rb

This PR adds empty modules and classes, to avoid YARD warnings, and to complete the generated documentation.

[docs] Avoid YARD warnings: define empty Faraday module, classes

---

lib/faraday_middleware/response/caching.rb

the 'fetch' method is no longer used.

Fix the incorrect description

---

lib/faraday_middleware/response/caching.rb
spec/unit/caching_spec.rb

Issue #132 notes that the caching middleware can generate keys which are too long when the input is a complex URL, leading to errors like `Errno::ENAMETOOLONG: File name too long @ rb_sysopen`. (The effective length limit depends on what cache driver you're using.)
At the moment, we use the normalised request URI as the cache key. The fixes the issue by using `Digest::SHA1.hexdigest` to hash the URLs, giving us a constant 20-byte result.
The trade-off of using a hash is that:
* there is the potential for collisions (as rare as they will realistically be!)
* performing a hash takes time

Hash request URIs before using them as a cache key

---

Gemfile
lib/faraday_middleware/response/follow_redirects.rb
spec/unit/follow_redirects_spec.rb

Fixed the issue that Authorization header remains during redirect to cross-site. 
This PR is related to #81. I added the commit that clear header only redirect to cross-site and that spec.

Clear Authorization header when redirecting cross-site

---

lib/faraday_middleware/response_middleware.rb

I got the following warnings with Ruby 2.7.
```
faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new
is deprecated; use `&block` instead
```

Ruby 2.7 warns on Proc.new with no block.

---

lib/faraday_middleware/gzip.rb
spec/unit/gzip_spec.rb

Sometimes empty bodies can be received together with a Content-Encoding of, for example, "gzip". I've come across this a few times working with external API:s which send a 304 (Do not modify), together with a empty body and Content-Encoding "Gzip".
With these changes, Faraday won't raise an unknown gzip format exception, but rather just not try to decompress the body.
Example of similar fix in okhttp: https://github.com/square/okhttp/issues/268

Fix support for empty bodies having Content-Encoding Gzip

---

.travis.yml
Gemfile
Gemfile-0.7.rb
Gemfile-0.8.rb
Gemfile-0.9.rb
README.md
faraday_middleware.gemspec
lib/faraday_middleware/backwards_compatibility.rb
lib/faraday_middleware/response/follow_redirects.rb
lib/faraday_middleware/response_middleware.rb
lib/faraday_middleware/version.rb
spec/helper.rb
spec/unit/gzip_spec.rb
spec/unit/parse_dates_spec.rb
spec/unit/parse_json_spec.rb
spec/unit/parse_marshal_spec.rb
spec/unit/parse_xml_spec.rb
spec/unit/parse_yaml_spec.rb

Faraday 0.16.0 compatibility, drops support for rubies < 2.3.0, jruby and rubinius

Update to faraday 1.0

---

.travis.yml

See #200 
This PR adds Ruby 2.7 to the build matrix.
With it in place, we can mine the output for 2.7 warnings, and quash them.

CI: Add 2.7

---

lib/faraday_middleware/rack_compatible.rb
lib/faraday_middleware/response/chunked.rb
lib/faraday_middleware/response/follow_redirects.rb
lib/faraday_middleware/response_middleware.rb
spec/unit/caching_spec.rb
spec/unit/follow_redirects_spec.rb
spec/unit/oauth_spec.rb

What the title says, see https://github.com/lostisland/faraday_middleware/issues/204
No meat on this, just rubocop warning fixes

chore: RuboCop lint Layout/EmptyLineAfterGuardClause

---

lib/faraday_middleware/request/oauth.rb
lib/faraday_middleware/response/chunked.rb
spec/unit/parse_dates_spec.rb

No meat on this, just rubocop warning fix for spaces after commas 
See https://github.com/lostisland/faraday_middleware/issues/200

 chore: RuboCop lint Layout/SpaceAfterComma

---

faraday_middleware.gemspec

This is the same as Faraday 1.0.
Before, it was not marked as restricted.

gemspec: Support Ruby 2.3+

---

.rubocop.yml
.rubocop_todo.yml

Closes #231 
See #204 
>  Perhaps we could take this into the known-and-ignored in the .rubocop.yml file - as opposed into the .rubocop_todo.yml file.

chore: Exclude 1 instance of Naming/PredicateName cop

---

.rubocop.yml
.rubocop_todo.yml

This PR promotes one TODO in RuboCop to an allowed thing:
- The middleware for Marshal.load MAY Marshal.load

chore: RuboCop-allow middleware for Marshal to Marshal.load

---

.rubocop_todo.yml
lib/faraday_middleware/rack_compatible.rb

Fix cop by: Turning String === name into name.is_a?(String)
See #204 
Closes #224

chore: RuboCop lint Style/CaseEquality

---

lib/faraday_middleware/gzip.rb
spec/unit/gzip_spec.rb

Supporting Ruby 1.8 has been dropped. #216

Avoid checking for encoding

---

lib/faraday_middleware/response/parse_json.rb

Supporting Ruby 1.8 has been dropped. #216
In Ruby 1.9+, string[nth] returns String.
No need to call String#chr.
---
FYI:
`String#chr` is only for compatibility with Ruby 1.8.
* In Ruby 1.8
- `string[nth]` returns `Integer|nil`
- Use `Integer#chr` for gets character
* In Ruby 1.9
- `string[nth]` returns `String|nil`
- `String#chr` has been implemented to work with the same code as Ruby 1.8
```ruby
'foo'[0].chr
```

Avoid String#chr

---

spec/helper.rb

`coverage/covered_percent` is for Cane gem
and Cane is removed at #202.
`cc-test-reporter` uses `coverage/.resultset.json`.
It is ECO, but not the default behavior of SimpleCov.
HTMLFormatter is SimpleCov's default formatter. (even in CI)`

Use default SimpleCov.formatter

---

lib/faraday_middleware/request/oauth.rb
spec/unit/oauth_spec.rb

Supporting Faraday v0.7 has been dropped.
`Faraday::Utils.build_nested_query` and `parse_nested_query`
are implemented in Faraday v0.8.0.
https://github.com/lostisland/faraday/commit/0d517cda5f

Faraday::Utils.(build|parse)_nested_query is defined

---

lib/faraday_middleware.rb
lib/faraday_middleware/redirect_limit_reached.rb
lib/faraday_middleware/response/follow_redirects.rb
spec/unit/follow_redirects_spec.rb

This PR moves the one specific error we define, to its expected file location.
To get autoloading to work:
- mention the class name in the main file (lib/faraday_middleware.rb)
- separate out to its own file
- ensure that a spec which was relying on that to be loaded had the main file loaded
See #198

Split error class to its own file

---

lib/faraday_middleware/response/parse_yaml.rb

And Syck is removed since Ruby 2.0.0.
---
I think, SafeYAML is also deprecated in Ruby 2.3+.
Use `YAML.safe_load` instead of `SafeYAML.load`.
```ruby
class ParseYaml < ResponseMiddleware
define_parser do |body, parser_options|
YAML.safe_load(body, **(parser_options || {}))
end
end
```
But there are two problems.
This makes a breaking change.
* SafeYAML
- `:deserialize_symbols`
- `:whitelisted_tags`
- `:custom_initializers`
- `:raise_on_unknown_tag`
* YAML
- `:permitted_classes`
- `:permitted_symbols`
- `:aliases`
- `:filename`
- `:fallback`
- `:symbolize_names`
Supporting all of this is a bit too complicated.
2.3, 2.4:
```ruby
def self.safe_load yaml, whitelist_classes = [], whitelist_symbols = [], aliases = false, filename = nil
```
2.5: `symbolize_names` is added as kwargs
```ruby
def …
```

Psych is default YAML Engine since Ruby 1.9.3

---

docs/caching_responses.md
docs/gzip.md
docs/index.md
docs/instrumentation.md
docs/method_override.md
docs/oauth.md

This PR imports all the wiki pages as Markdown documents into the repository.
Excluded: "Changes in 0.8".
See #250.

Import wiki pages as Markdown

---

lib/faraday_middleware/version.rb

This PR sets the version number to `1.0.0.rc1` in order to be able to release a Release Candidate.
See #200 - this will make it possible to try out the "1.0" release before 1.0.0 is released.

Set version to 1.0.0.rc1

---

Gemfile

Fixes the following: 
```
FaradayMiddleware::FollowRedirects redirects on 308
Failure/Error: response = @app.call(env)
NoMethodError:
undefined method `close' for #<StubSocket:0x000055fda3b90950>
Did you mean?  closed?
clone
```
note, this issue's only on faraday 1.0.1
I'm happy to do anything testing-wise this requires if you all want it in. 
see https://github.com/bblimke/webmock/issues/683

update webmock to min 2.3

---

lib/faraday_middleware/response_middleware.rb

This is from that existing issue that's open, #160.
Fixes #160

Use wrapped exception in Faraday::ParsingError to improve legibility of the error

---

Gemfile

the cops in issue 256 need a minimum rubocop 0.80 so maybe it makes sense to do this first, I dunno.

bump rubocop-performance

---

.codeclimate.yml
.rubocop_codeclimate.yml

- Add CodeClimate YAML configuration file
- Point out 0.81 "channel" for most-modern cops
- Add a RuboCop CodeClimate-specific YAML configuration file: Disable the `require` YAML setting, which pulls in unsupported-in-CodeClimate Plugins we also use
Fixes #260

Configure RuboCop for CodeClimate

---

.codeclimate.yml
.github/workflows/ci.yml
README.md

This PR removes CodeClimate.
The badge has been showing grey for a while, and nobody has acted on that. The reason why the badge was grey: CC is unable to run a configured RuboCop, with a single plugin.
If we need to do spot-checks for metrics, we can use rubycritic in a focused sitting.
TODO:

Drop CodeClimate

---

.github/workflows/ci.yml

This is in order to go faster. Borrowed from the Faraday CI configuration. 
**Result**: From 4 min to 40 s.
Fixes #271

GitHub Actions: use ruby/setup-ruby@v1

---

.github/workflows/ci.yml
README.md

Our Code of Conduct includes a note on inclusive language, and changing the name of the default branch is part of upholding that value.
In the GitHub documentation about renames: https://docs.github.com/en/github/administering-a-repository/renaming-a-branch
> When you rename a branch on GitHub, any URLs that contain the old branch name are automatically redirected to the equivalent URL for the renamed branch. Branch protection policies are also updated, as well as the base branch for open pull requests (including those for forks) and draft releases. After the rename is complete, GitHub provides instructions on the repository's home page directing contributors to update their local Git environments.
TODO:

Update default branch name to main

---

lib/faraday_middleware/response/caching.rb
spec/unit/caching_spec.rb

This implementation allows users to define its own set of status codes for caching as opposed to sticking to a set of predefined CACHEABLE_STATUS_CODE constant. Nonetheless, user defined status code has to be within the list of predefined CACHEABLE_STATUS_CODE constant.

Allow users to define its own set of Cacheable Status Code when using Faraday Middleware Cache

---

README.md

How to get reach there in another way?

Add link to `awesome-faraday` into README

---

Gemfile

While reading about a ReDOS in addressable, I learned that this repository no longer uses the gem.
Removing from Gemfile.

fix: drop unused addressable gem

---

.github/workflows/ci.yml
.github/workflows/publish.yml
Gemfile

Updates checkout action version.  Fixes unsupported use of actions/ruby-setup
I know the repo is deprecated, but I figured the build should run for those who might be using this with an older version of faraday.

Adds Ruby 3.2 to CI. 

---

README.md

This PR uses the badge from GH Actions.

README: use GitHub Actions-based badge

---

.github/workflows/ci.yml
.github/workflows/publish.yml

This PR changes the test CI setup to use as much knowledge as possible from the setup-ruby GH Action, keeping version number and such out of the file. For the yard-junk lint check, I did some steps.
Perhaps we can stop having the yard-junk check at all, we are not actively working on the docs of this project.

CI: Trust ruby/setup-ruby to install gems

---

.github/workflows/ci.yml

This PR removes yard-junk from the CI process. It had collected too much baggage needs to run on Ruby 2.6.
Also, rubocop can have default arguments.

Ci drop yard junk
