lostisland/faraday_middleware

lib/faraday_middleware/request/oauth2.rb, spec/unit/oauth2_spec.rb
As discussed in #130.
Still missing updated documentation - I'm not sure what the procedure is for editing the wiki or the timeline for doing it against releasing changes. Let me know if you have a preferred way of handling that.
=> Add token_type option for specifying method of adding OAuth2 tokens

lib/faraday_middleware/response/follow_redirects.rb, spec/integration/follow_redirects_spec.rb, spec/unit/follow_redirects_spec.rb
=> Add support for 308 status code (redirect)

.travis.yml
- Drop sudo: false - a removed Travis setting
=> CI: Add 2.6.3

spec/helper.rb, spec/integration/follow_redirects_spec.rb, spec/unit/caching_spec.rb, spec/unit/chunked_spec.rb, spec/unit/encode_json_spec.rb, spec/unit/follow_redirects_spec.rb, spec/unit/gzip_spec.rb, spec/unit/mashify_spec.rb, spec/unit/method_override_spec.rb, spec/unit/oauth2_spec.rb, spec/unit/oauth_spec.rb, spec/unit/parse_dates_spec.rb, spec/unit/parse_json_spec.rb, spec/unit/parse_marshal_spec.rb, spec/unit/parse_xml_spec.rb, spec/unit/parse_yaml_spec.rb, spec/unit/rashify_spec.rb
This PR uses https://relishapp.com/rspec/rspec-core/v/3-8/docs/configuration/zero-monkey-patching-mode
=> RSpec: disable_monkey_patching

lib/faraday_middleware/response_middleware.rb, spec/unit/response_middleware_spec.rb
Here's a small unit test addition, to cover the comment in #189
=> Add ResponseMiddleware.define_parser unit test

Gemfile
=> chore: RuboCop lint Bundler/OrderedGems

Rakefile, faraday_middleware.gemspec, lib/faraday_middleware/request/method_override.rb, lib/faraday_middleware/request/oauth2.rb, lib/faraday_middleware/response/parse_dates.rb, lib/faraday_middleware/response/parse_json.rb, spec/unit/caching_spec.rb, spec/unit/chunked_spec.rb, spec/unit/encode_json_spec.rb, spec/unit/follow_redirects_spec.rb, spec/unit/gzip_spec.rb, spec/unit/mashify_spec.rb, spec/unit/method_override_spec.rb, spec/unit/oauth2_spec.rb, spec/unit/oauth_spec.rb, spec/unit/parse_dates_spec.rb, spec/unit/parse_json_spec.rb, spec/unit/parse_marshal_spec.rb, spec/unit/parse_xml_spec.rb, spec/unit/parse_yaml_spec.rb, spec/unit/rashify_spec.rb
This PR is a linting Pull Request, connected to #200. 
In order to keep the PRs easy to review, this is just 1 Cop at a time.
```
$ rubocop --require rubocop-performance --format progress --only Style/StringLiterals -a
Inspecting 42 files
..........................................
42 files inspected, no offenses detected
```
=> RuboCop: only Style/StringLiterals

spec/unit/caching_spec.rb
=> chore: RuboCop lint Layout/ArgumentAlignment

spec/unit/caching_spec.rb
=> chore: RuboCop lint Layout/ArrayAlignment

spec/unit/oauth_spec.rb
=> chore: RuboCop lint Layout/BlockEndNewline

faraday_middleware.gemspec
see https://github.com/lostisland/faraday_middleware/issues/200
=> Fix Layout/EmptyLineAfterMagicComment

spec/unit/encode_json_spec.rb
yeah yeah, you know which issue it is anyway :)
See #204
=> Fix Layout/EmptyLineBetweenDefs

lib/faraday_middleware/gzip.rb
see https://github.com/lostisland/faraday_middleware/issues/204
=> Fix Layout/ElseAlignment cop

lib/faraday_middleware/request/oauth.rb, lib/faraday_middleware/response/caching.rb, spec/unit/chunked_spec.rb, spec/unit/encode_json_spec.rb, spec/unit/method_override_spec.rb, spec/unit/oauth2_spec.rb, spec/unit/oauth_spec.rb, spec/unit/parse_json_spec.rb
Sorry @olleolleolle, try this instead of the https://github.com/lostisland/faraday_middleware/pull/212 please
=> Fix Layout/SpaceInsideBlockBraces cop

lib/faraday_middleware/request/method_override.rb, lib/faraday_middleware/request/oauth2.rb
Per https://github.com/lostisland/faraday_middleware/issues/204
=> Fix Layout/EmptyLinesAroundClassBody cop

.rubocop_todo.yml, lib/faraday_middleware/response/parse_json.rb
=> Fix Lint/Loop cop

.rubocop_todo.yml, Rakefile
=> Fix Naming/VariableNumber cop

.rubocop_todo.yml, lib/faraday_middleware/request/encode_json.rb, lib/faraday_middleware/request/oauth2.rb, spec/unit/caching_spec.rb, spec/unit/oauth_spec.rb
=> Fix Style/GuardClause cop warnings

.rubocop_todo.yml, lib/faraday_middleware/rack_compatible.rb
=> Fix Style/NumericPredicate cop

.rubocop_todo.yml, lib/faraday_middleware/rack_compatible.rb
=> Fix Naming/ConstantName cop

.rubocop_todo.yml, lib/faraday_middleware/request/oauth.rb
=> Fix Style/MultilineTernaryOperator

.rubocop_todo.yml, lib/faraday_middleware/response/caching.rb
I think it should be this? 
See #204
=> Fix Lint/AssignmentInCondition cop

.rubocop_todo.yml, spec/helper.rb, spec/unit/caching_spec.rb
This PR fixes 2 rubocop cops.
See #204
=> chore: Style/FormatString, Style/FormatStringToken

Gemfile
This PR drops a commented-out line in the Gemfile.
=> chore: Drop commented-out code

.rubocop.yml
=> Configure cops in .rubocop.yml

lib/faraday_middleware/response/caching.rb, lib/faraday_middleware/response/follow_redirects.rb, spec/unit/caching_spec.rb, spec/unit/mashify_spec.rb, spec/unit/oauth2_spec.rb
This PR attempts to make the linting step green. 🟢 
Fixes #267
=> Linting code

README.md
corrected the spelling of middleware
=> correction in README.md
